[package]
name = "FlowDB-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snap = "1.1.0"
crossbeam-queue = "0.3.8"
log = "0.4.20"
openssl = "0.10.57"